# Terraform Backend Configuration
# Generated by deploy.py

terraform {
  backend "s3" {
    bucket         = "alico155317030732-fortigate-terraform-state"
    key            = "fortigate-ha/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "alico155317030732-fortigate-terraform-locks"
    encrypt        = true
    profile        = "renaws"
  }
}
